Repository su-its/ams-frontend, pull requests merged in 2021-03, with the labels that each got.

#12 websocketとvueを暫定的に入れてみた。
  .editorconfig
  LICENSE
  about.html
  css/bulma.min.css
  css/font-awesome.min.css
  css/main.css
  fonts/FontAwesome.otf
  fonts/fontawesome-webfont.eot
  fonts/fontawesome-webfont.svg
  fonts/fontawesome-webfont.ttf
  fonts/fontawesome-webfont.woff
  fonts/fontawesome-webfont.woff2
  img/logo.png
  index.html
  js/main.js
  log.html
Labels: Priority:High

#15 Nuxt化しました
  .babelrc
  .editorconfig
  .env_sample
  .eslintrc.json
  .gitignore
  .textlintrc
  README.md
  assets/README.md
  assets/common.scss
  components/README.md
  docker-compose.yml
  docker/nodejs/Dockerfile
  docker/nodejs/docker-entrypoint.sh
  docs/config/Redpen-config.xml
  docs/config/spellcheck.yml
  jest.config.js
  layouts/README.md
  middleware/README.md
  mock/about.html
  mock/css/bulma.min.css
  mock/css/font-awesome.min.css
  mock/css/main.css
  mock/fonts/FontAwesome.otf
  mock/fonts/fontawesome-webfont.eot
  mock/fonts/fontawesome-webfont.svg
  mock/fonts/fontawesome-webfont.ttf
  mock/fonts/fontawesome-webfont.woff
  mock/fonts/fontawesome-webfont.woff2
  mock/img/favicon.ico
  mock/img/logo.png
  mock/index.html
  mock/js/main.js
  mock/log.html
  nuxt.config.js
  package-lock.json
  package.json
  pages/README.md
  pages/index.vue
  plugins/README.md
  static/README.md
  static/favicon.ico
  static/logo.png
  store/README.md
  test/Logo.spec.js
  textlint.sh
  tsconfig.json
Labels: enhancement

#17 スマホのレイアウト対応版のモックアップ
  mock/about.html
  mock/css/main.css
  mock/index.html
  mock/log.html
Labels: Priority:High

#20 現在の時点で必要最低限のドキュメントを作成
  CONTRIBUTING.md
  README.md
  docs/PJ_map/AMS_MAP.png
  docs/PJ_map/AMS_MAP.puml
Labels: enhancement

#22 基本的な機能は一通り備えました
  .eslintrc.json
  .gitignore
  .textlintrc
  assets/common.scss
  components/AccessLogCard.vue
  components/ErrorCard.vue
  components/Footer.vue
  components/Header.vue
  components/InRoomUsers.vue
  components/Navigation.vue
  components/UserInfo.vue
  docs/nuxt_lifecycle.md
  docs/改善案.md
  layouts/default.vue
  layouts/error.vue
  mock/404.html
  mock/index.html
  mock/log.html
  nuxt.config.js
  package-lock.json
  package.json
  pages/about.vue
  pages/index.vue
  pages/log.vue
  plugins/lodash.js
  store/logging.js
  store/version.js
  textlint.sh
  tsconfig.json
Labels: Priority:High, enhancement

#28 レイアウトの修正を行いました。不要なモジュールの削除も行いました
  .eslintrc.json
  .textlintrc
  CONTRIBUTING.md
  README.md
  assets/README.md
  assets/common.scss
  components/AccessLogCard.vue
  components/CSV/CSVDownload.vue
  components/CSV/CustomCSV.vue
  components/CSV/DefaultCSV.vue
  components/Common/ErrorCard.vue
  components/Common/Footer.vue
  components/Common/Header.vue
  components/Common/Navigation.vue
  components/Common/NoContent.vue
  components/README.md
  docs/PJ_map/AMS_MAP.png
  docs/PJ_map/AMS_MAP.puml
  docs/config/Redpen-config.xml
  docs/nuxt_lifecycle.md
  docs/改善案.md
  jest.config.js
  layouts/README.md
  layouts/default.vue
  layouts/error.vue
  middleware/README.md
  mock/404.html
  mock/about.html
  mock/css/bulma.min.css
  mock/css/font-awesome.min.css
  mock/css/main.css
  mock/fonts/FontAwesome.otf
  mock/fonts/fontawesome-webfont.eot
  mock/fonts/fontawesome-webfont.svg
  mock/fonts/fontawesome-webfont.ttf
  mock/fonts/fontawesome-webfont.woff
  mock/fonts/fontawesome-webfont.woff2
  mock/img/favicon.ico
  mock/img/logo.png
  mock/index.html
  mock/js/main.js
  mock/log.html
  mock/log_nodata.html
  nuxt.config.js
  package-lock.json
  package.json
  pages/README.md
  pages/about.vue
  pages/index.vue
  pages/log.vue
  plugins/README.md
  plugins/common.js
  static/README.md
  store/README.md
  store/logging.js
  tsconfig.json
Labels: 主要機能

#35 ドキュメントのCIの追加
  .github/workflows/eslint-review.yml
  .github/workflows/text_ci.yml
  .textlintignore
  .textlintrc
  README.md
  docs/AMS_MAP/AMS_MAP.png
  docs/AMS_MAP/AMS_MAP.puml
  docs/PJ_map/AMS_MAP.png
  docs/PJ_map/AMS_MAP.puml
  docs/config/Redpen-config.xml
  docs/config/WEB+DB_PRESS.yml
  docs/config/spellcheck.yml
  package-lock.json
  package.json
Labels: documentation

#34 PM2に乗せるための改修を行った
  ecosystem.config.js
  package.json
Labels: 優先度：高
